use image::DynamicImage;
use texture_packer::{
    exporter::ImageExporter, importer::ImageImporter, texture::Texture, TexturePacker,
    TexturePackerConfig,
};
use wasm_bindgen::prelude::*;

use crate::encode::{encode_image_with_format_str, extension_for_format};
use crate::js_input::{parse_image_entries, ImageEntry};

const MAX_SHEET_DIMENSION: u32 = 8192;

#[wasm_bindgen]
pub struct SpriteSheetResult {
    image: Vec<u8>,
    css: String,
    width: u32,
    height: u32,
}

#[wasm_bindgen]
impl SpriteSheetResult {
    #[wasm_bindgen(getter)]
    pub fn image(&self) -> Vec<u8> {
        self.image.clone()
    }

    #[wasm_bindgen(getter)]
    pub fn css(&self) -> String {
        self.css.clone()
    }

    #[wasm_bindgen(getter)]
    pub fn width(&self) -> u32 {
        self.width
    }

    #[wasm_bindgen(getter)]
    pub fn height(&self) -> u32 {
        self.height
    }
}

/// 複数画像を 1 枚のスプライトシートに結合し、画像バイナリと CSS を返す。
#[wasm_bindgen]
pub fn generate_css_sprite(
    images: JsValue,
    sprite_filename: &str,
    output_format: &str,
) -> Result<SpriteSheetResult, JsValue> {
    let entries = parse_image_entries(&images)?;
    let sheet_name = if sprite_filename.trim().is_empty() {
        format!("sprite.{}", extension_for_format(output_format)?)
    } else {
        sprite_filename.to_string()
    };

    let config = TexturePackerConfig {
        max_width: MAX_SHEET_DIMENSION,
        max_height: MAX_SHEET_DIMENSION,
        allow_rotation: false,
        trim: true,
        border_padding: 1,
        texture_padding: 1,
        texture_extrusion: 0,
        texture_outlines: false,
        force_max_dimensions: false,
        ..Default::default()
    };

    let mut packer = TexturePacker::new_skyline(config);

    for entry in &entries {
        let texture = ImageImporter::import_from_memory(&entry.data)
            .map_err(|e| JsValue::from_str(&format!("{}: {e}", entry.name)))?;
        packer
            .pack_own(entry.name.clone(), texture)
            .map_err(|e| JsValue::from_str(&format!("pack {}: {e:?}", entry.name)))?;
    }

    if packer.get_frames().is_empty() {
        return Err(JsValue::from_str("no frames were packed"));
    }

    let atlas = ImageExporter::export(&packer, None)
        .map_err(|e| JsValue::from_str(&format!("export atlas: {e}")))?;

    let width = packer.width();
    let height = packer.height();
    let image = encode_image_with_format_str(&atlas, output_format, 90)?;
    let css = build_sprite_css(&entries, &packer, &sheet_name);

    Ok(SpriteSheetResult {
        image,
        css,
        width,
        height,
    })
}

fn build_sprite_css(
    entries: &[ImageEntry],
    packer: &TexturePacker<'_, DynamicImage, String>,
    sheet_name: &str,
) -> String {
    let mut css = String::from("/* Generated by tool-kit */\n");
    css.push_str(&format!(
        ".sprite-sheet {{\n  background-image: url('{sheet_name}');\n  background-repeat: no-repeat;\n}}\n\n"
    ));

    for entry in entries {
        let Some(frame) = packer.get_frame(&entry.name) else {
            continue;
        };
        let class = css_class_name(&entry.name);
        let w = frame.frame.w;
        let h = frame.frame.h;
        css.push_str(&format!(
            ".{class} {{\n  width: {w}px;\n  height: {h}px;\n  background-image: url('{sheet_name}');\n  background-repeat: no-repeat;\n  background-position: -{}px -{}px;\n}}\n\n",
            frame.frame.x, frame.frame.y
        ));
    }

    css
}

fn css_class_name(name: &str) -> String {
    let stem = name
        .rsplit_once('.')
        .map(|(s, _)| s)
        .unwrap_or(name);
    let sanitized: String = stem
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect();
    format!("sprite-{}", sanitized.to_ascii_lowercase())
}
